// Generated from Lichess translation/source/learn.xml.
export const LEARN_EN = {
  "learnChess": "Learn chess",
  "byPlaying": "by playing!",
  "menu": "Menu",
  "progressX": "Progress: %s",
  "resetMyProgress": "Reset my progress",
  "youWillLoseAllYourProgress": "You will lose all your progress!",
  "play": "play!",
  "chessPieces": "Chess pieces",
  "theRook": "The rook",
  "itMovesInStraightLines": "It moves in straight lines",
  "rookIntro": "The rook is a powerful piece. Are you ready to command it?",
  "rookGoal": "Click on the rook\nto bring it to the star!",
  "grabAllTheStars": "Grab all the stars!",
  "theFewerMoves": "The fewer moves you make,\nthe more points you win!",
  "useTwoRooks": "Use two rooks\nto speed things up!",
  "rookComplete": "Congratulations! You have successfully mastered the rook.",
  "theBishop": "The bishop",
  "itMovesDiagonally": "It moves diagonally",
  "bishopIntro": "Next we will learn how to manoeuvre a bishop!",
  "youNeedBothBishops": "One light-squared bishop,\none dark-squared bishop.\nYou need both!",
  "bishopComplete": "Congratulations! You can command a bishop.",
  "theQueen": "The queen",
  "queenCombinesRookAndBishop": "Queen = rook + bishop",
  "queenIntro": "The most powerful chess piece enters. Her majesty the queen!",
  "queenComplete": "Congratulations! Queens have no secrets for you.",
  "theKing": "The king",
  "theMostImportantPiece": "The most important piece",
  "kingIntro": "You are the king. If you fall in battle, the game is lost.",
  "theKingIsSlow": "The king is slow.",
  "lastOne": "Last one!",
  "kingComplete": "You can now command the commander!",
  "theKnight": "The knight",
  "itMovesInAnLShape": "It moves in an L shape",
  "knightIntro": "Here's a challenge for you. The knight is... a tricky piece.",
  "knightsHaveAFancyWay": "Knights have a fancy way\nof jumping around!",
  "knightsCanJumpOverObstacles": "Knights can jump over obstacles!\nEscape and vanquish the stars!",
  "knightComplete": "Congratulations! You have mastered the knight.",
  "thePawn": "The pawn",
  "itMovesForwardOnly": "It moves forward only",
  "pawnIntro": "Pawns are weak, but they pack a lot of potential.",
  "pawnsMoveOneSquareOnly": "Pawns move one square only.\nBut when they reach the other side of the board, they become a stronger piece!",
  "mostOfTheTimePromotingToAQueenIsBest": "Most of the time promoting to a queen is the best.\nBut sometimes a knight can come in handy!",
  "pawnsMoveForward": "Pawns move forward,\nbut capture diagonally!",
  "captureThenPromote": "Capture, then promote!",
  "useAllThePawns": "Use all the pawns!\nNo need to promote.",
  "aPawnOnTheSecondRank": "A pawn on the second rank can move 2 squares at once!",
  "grabAllTheStarsNoNeedToPromote": "Grab all the stars!\nNo need to promote.",
  "pawnComplete": "Congratulations! Pawns have no secrets for you.",
  "pawnPromotion": "Pawn promotion",
  "yourPawnReachedTheEndOfTheBoard": "Your pawn reached the end of the board!",
  "itNowPromotesToAStrongerPiece": "It now promotes to a stronger piece.",
  "selectThePieceYouWant": "Select the piece you want!",
  "fundamentals": "Fundamentals",
  "capture": "Capture",
  "takeTheEnemyPieces": "Take the enemy pieces",
  "captureIntro": "Identify the opponent's undefended pieces, and capture them!",
  "takeTheBlackPieces": "Take the black pieces!",
  "takeTheBlackPiecesAndDontLoseYours": "Take the black pieces!\nAnd don't lose yours.",
  "captureComplete": "Congratulations! You know how to fight with chess pieces!",
  "protection": "Protection",
  "keepYourPiecesSafe": "Keep your pieces safe",
  "protectionIntro": "Identify the pieces your opponent attacks, and defend them!",
  "protectionComplete": "Congratulations! A piece you don't lose is a piece you win!",
  "escape": "You're under attack!\nEscape the threat!",
  "noEscape": "There is no escape,\nbut you can defend!",
  "dontLetThemTakeAnyUndefendedPiece": "Don't let them take\nany undefended piece!",
  "combat": "Combat",
  "captureAndDefendPieces": "Capture and defend pieces",
  "combatIntro": "A good warrior knows both attack and defence!",
  "combatComplete": "Congratulations! You know how to fight with chess pieces!",
  "checkInOne": "Check in one",
  "attackTheOpponentsKing": "Attack the opponent's king",
  "checkInOneIntro": "To check your opponent, attack their king. They must defend it!",
  "checkInOneGoal": "Aim at the opponent's king\nin one move!",
  "checkInOneComplete": "Congratulations! You checked your opponent, forcing them to defend their king!",
  "outOfCheck": "Out of check",
  "defendYourKing": "Defend your king",
  "outOfCheckIntro": "You are in check! You must escape or block the attack.",
  "escapeWithTheKing": "Escape with the king!",
  "theKingCannotEscapeButBlock": "The king cannot escape,\nbut you can block the attack!",
  "youCanGetOutOfCheckByTaking": "You can get out of check\nby taking the attacking piece.",
  "thisKnightIsCheckingThroughYourDefenses": "This knight is checking\nthrough your defences!",
  "escapeOrBlock": "Escape with the king\nor block the attack!",
  "outOfCheckComplete": "Congratulations! Your king must never be taken, so make sure you can defend against a check!",
  "mateInOne": "Mate in one",
  "defeatTheOpponentsKing": "Defeat the opponent's king",
  "mateInOneIntro": "You win when your opponent cannot defend against a check.",
  "attackYourOpponentsKing": "Attack your opponent's king\nin a way that cannot be defended!",
  "mateInOneComplete": "Congratulations! That is how you win chess games!",
  "intermediate": "Intermediate",
  "boardSetup": "Board setup",
  "howTheGameStarts": "How the game starts",
  "boardSetupIntro": "The two armies face each other, ready for the battle.",
  "thisIsTheInitialPosition": "This is the initial position\nof every game of chess!\nMake any move to continue.",
  "firstPlaceTheRooks": "First place the rooks!\nThey go in the corners.",
  "thenPlaceTheKnights": "Then place the knights!\nThey go next to the rooks.",
  "placeTheBishops": "Place the bishops!\nThey go next to the knights.",
  "placeTheQueen": "Place the queen!\nShe goes on her own colour.",
  "placeTheKing": "Place the king!\nRight next to his queen.",
  "pawnsFormTheFrontLine": "Pawns form the front line.\nMake any move to continue.",
  "boardSetupComplete": "Congratulations! You know how to set up the chess board.",
  "castling": "Castling",
  "theSpecialKingMove": "The special king move",
  "castlingIntro": "Bring your king to safety, and deploy your rook for attack!",
  "castleKingSide": "Move your king two squares\nto castle king-side!",
  "castleQueenSide": "Move your king two squares\nto castle queen-side!",
  "theKnightIsInTheWay": "The knight is in the way!\nMove it, then castle king-side.",
  "castleKingSideMovePiecesFirst": "Castle king-side!\nYou need to move out pieces first.",
  "castleQueenSideMovePiecesFirst": "Castle queen-side!\nYou need to move out pieces first.",
  "youCannotCastleIfMoved": "You cannot castle if\nthe king has already moved\nor the rook has already moved.",
  "youCannotCastleIfAttacked": "You cannot castle if\nthe king is attacked on the way.\nBlock the check then castle!",
  "findAWayToCastleKingSide": "Find a way to\ncastle king-side!",
  "findAWayToCastleQueenSide": "Find a way to\ncastle queen-side!",
  "castlingComplete": "Congratulations! You should almost always castle in a game.",
  "theSpecialPawnMove": "The special pawn move",
  "enPassantIntro": "When the opponent's pawn moves two squares, you can still take it as if it had only moved one square.",
  "blackJustMovedThePawnByTwoSquares": "Black just moved the pawn\nby two squares!\nTake it en passant.",
  "enPassantOnlyWorksImmediately": "En passant only works\nimmediately after the opponent\nmoved the pawn.",
  "enPassantOnlyWorksOnFifthRank": "En passant only works\nif your pawn is on the 5th rank.",
  "takeAllThePawnsEnPassant": "Take all the pawns en passant!",
  "enPassantComplete": "Congratulations! You can now take en passant.",
  "stalemate": "Stalemate",
  "theGameIsADraw": "The game is a draw",
  "stalemateIntro": "When a player is not in check and does not have a legal move, it's a stalemate. The game is drawn: no one wins, no one loses.",
  "stalemateGoal": "To stalemate black:\n- Black cannot move anywhere\n- There is no check.",
  "stalemateComplete": "Congratulations! Better be stalemated than checkmated!",
  "advanced": "Advanced",
  "pieceValue": "Piece value",
  "evaluatePieceStrength": "Evaluate piece strength",
  "pieceValueIntro": "Pieces with high mobility have a higher value!\nQueen = 9\nRook = 5\nBishop = 3\nKnight = 3\nPawn = 1\nThe king is priceless! Losing it means losing the game.",
  "queenOverBishop": "Take the piece\nwith the highest value!\nQueen > Bishop",
  "pieceValueExchange": "Take the piece with the highest value!\nDo not exchange\na higher valued piece for a less valuable one.",
  "pieceValueLegal": "Take the piece\nwith the highest value!\nMake sure your move is legal!",
  "takeThePieceWithTheHighestValue": "Take the piece\nwith the highest value!",
  "pieceValueComplete": "Congratulations! You know the value of material!\nQueen = 9\nRook = 5\nBishop = 3\nKnight = 3\nPawn = 1",
  "checkInTwo": "Check in two",
  "twoMovesToGiveCheck": "Two moves to give a check",
  "checkInTwoIntro": "Find the right combination of two moves that checks the opponent's king!",
  "checkInTwoGoal": "Threaten the opponent's king\nin two moves!",
  "checkInTwoComplete": "Congratulations! You checked your opponent, forcing them to defend their king!",
  "whatNext": "What next?",
  "youKnowHowToPlayChess": "You know how to play chess, congratulations! Do you want to become a stronger player?",
  "register": "Register",
  "getAFreeLichessAccount": "Get a free Lichess account",
  "practice": "Practise",
  "learnCommonChessPositions": "Learn common chess positions",
  "puzzles": "Puzzles",
  "exerciseYourTacticalSkills": "Exercise your tactical skills",
  "videos": "Videos",
  "watchInstructiveChessVideos": "Watch instructive chess videos",
  "playPeople": "Play people",
  "opponentsFromAroundTheWorld": "Opponents from around the world",
  "playMachine": "Play machine",
  "testYourSkillsWithTheComputer": "Test your skills with the computer",
  "letsGo": "Let's go!",
  "stageX": "Stage %s",
  "awesome": "Awesome!",
  "excellent": "Excellent!",
  "greatJob": "Great job!",
  "perfect": "Perfect!",
  "outstanding": "Outstanding!",
  "wayToGo": "Way to go!",
  "yesYesYes": "Yes, yes, yes!",
  "youreGoodAtThis": "You're good at this!",
  "nailedIt": "Nailed it.",
  "rightOn": "Right on!",
  "stageXComplete": "Stage %s complete",
  "next": "Next",
  "nextX": "Next: %s",
  "backToMenu": "Back to menu",
  "puzzleFailed": "Puzzle failed!",
  "retry": "Retry"
} as const;
