#!/usr/bin/env bash

set -e

cd "$(dirname "${BASH_SOURCE:-$0}")/.build"

ROOT_DIR="$(git rev-parse --show-toplevel)"
if [ -f "$ROOT_DIR/.node-version" ]; then
  MIN_NODE="$(cat "$ROOT_DIR/.node-version")"
else
  MIN_NODE="v$(node -p "require('$ROOT_DIR/package.json').engines.node.match(/[0-9]+/)[0]").0.0"
fi
CUR_NODE=$(node -v 2>/dev/null || echo "v0.0.0")
LOWEST="$(printf "%s\n%s" "$MIN_NODE" "$CUR_NODE" | sort -V | head -n 1)"
if [ "$LOWEST" != "$MIN_NODE" ]; then
  echo "Nodejs $MIN_NODE or later is required."
  exit 1
fi

if ! yes | pnpm install >/dev/null 2>&1; then
  pnpm install --loglevel debug
  exit $?
fi

node --no-warnings src/main.ts "$@"
