"use client";

import { useCallback, useState } from "react";
import { usePrivy } from "@privy-io/react-auth";
import { decodeEventLog } from "viem";
import { getWalletAddress } from "@/lib/user";
import { awaitReceipt, publicClientForChain } from "@/lib/trade/receipt";
import { useEvmSendBatch } from "@/hooks/use-evm-send";
import { KING_OF_NIGHT_V5_ABI } from "@/lib/vault/king-of-night-v5-abi";
import { claimCall, settleCall, startGameCalls, wagerCalls } from "@/lib/vault/v5-calls";
import { VAULT_CHAIN_ID, vaultContractAddress } from "@/lib/vault/contract";
import { vaultLog } from "@/features/casino/lib/last-standing/log";
import { registerVaultTransaction } from "@/features/casino/lib/vault-api";

// The compiled artifact, never a transcription: a hand-typed GameStarted with
// four fields hashed to a topic that matched no log and lost every gameId.
// v5's is generated by scripts/generate-vault-v5-abi.mjs.
const VAULT_ABI = KING_OF_NIGHT_V5_ABI;

const contractAddress = vaultContractAddress;

// The gameId is only knowable from the receipt: startGame() returns it, but a
// return value is not readable from a sent transaction, so it comes off the
// GameStarted log instead.
function gameIdFromReceipt(logs: readonly { data: string; topics: string[] }[]): number | null {
  for (const log of logs) {
    try {
      const decoded = decodeEventLog({
        abi: VAULT_ABI,
        data: log.data as `0x${string}`,
        topics: log.topics as [`0x${string}`, ...`0x${string}`[]],
      });
      if (decoded.eventName === "GameStarted") {
        return Number((decoded.args as { gameId: bigint }).gameId);
      }
    } catch {
      // Not one of ours; every receipt carries logs from other contracts too.
    }
  }
  return null;
}

/**
 * startGame / wager / settle / claim, signed by the user's own embedded wallet. The
 * backend never holds keys or signs on their behalf. Each waits for on-chain
 * confirmation so the caller's refetch reflects the result.
 */
export function useVaultActions() {
  const { user } = usePrivy();
  // Every action is one atomic sponsored user operation. An ERC-20 stake needs
  // an allowance before the vault can pull it, and sending the two in sequence
  // against a 60-second clock leaves a window where the game settles in between
  // and the second call reverts on an allowance that is already standing.
  // Nothing here prompts the player: signing is headless.
  const sendBatch = useEvmSendBatch();
  const [starting, setStarting] = useState(false);
  const [wagering, setWagering] = useState(false);
  const [claiming, setClaiming] = useState(false);
  const [settling, setSettling] = useState(false);

  const owner = useCallback((): `0x${string}` => {
    const address = getWalletAddress(user, "ethereum");
    if (!address) throw new Error("No EVM wallet is connected.");
    return address as `0x${string}`;
  }, [user]);

  /**
   * Opens a game at `stake` base units of the game asset (USDC, 6 decimals).
   *
   * The stake becomes that game's own minimum for everyone who joins, so it is
   * the number the sheet shows, not a floor.
   */
  const startGame = useCallback(
    async (stake: bigint): Promise<{ hash: string; gameId: number | null }> => {
      const address = owner();
      setStarting(true);
      try {
        const client = publicClientForChain(VAULT_CHAIN_ID);
        const hash = await sendBatch(startGameCalls(contractAddress(), stake), VAULT_CHAIN_ID);
        const receipt = await awaitReceipt(client, hash, "Your game");
        // Tell the service about the hash so it indexes this game now rather
        // than when its own poll reaches the block. It closes the window where
        // a game the player has just paid for is not yet in /games.
        void registerVaultTransaction(hash);
        const gameId = gameIdFromReceipt(receipt?.logs ?? []);
        vaultLog("tx startGame confirmed", { hash, gameId, stake: stake.toString(), address });
        return { hash, gameId };
      } finally {
        setStarting(false);
      }
    },
    [owner, sendBatch]
  );

  /** Joins a game with `amount` base units, which must clear its own minWager. */
  const wager = useCallback(
    async (gameId: number, amount: bigint): Promise<string> => {
      const address = owner();
      setWagering(true);
      try {
        const client = publicClientForChain(VAULT_CHAIN_ID);
        const hash = await sendBatch(wagerCalls(contractAddress(), gameId, amount), VAULT_CHAIN_ID);
        await awaitReceipt(client, hash, "Your wager");
        void registerVaultTransaction(hash);
        vaultLog("tx wager confirmed", { gameId, hash, amount: amount.toString(), address });
        return hash;
      } finally {
        setWagering(false);
      }
    },
    [owner, sendBatch]
  );

  /**
   * Collects a payout settlement could not push, in one asset.
   *
   * Settlement pays the winner and the starter directly; only a transfer that
   * fails is credited to pendingWithdrawals[token][account], and this sweeps
   * it. v4's claim() took no argument and is absent from the v5 bytecode, so
   * the asset is not optional.
   */
  const claim = useCallback(
    async (token?: string): Promise<string> => {
      const address = owner();
      setClaiming(true);
      try {
        const client = publicClientForChain(VAULT_CHAIN_ID);
        const hash = await sendBatch([claimCall(contractAddress(), token)], VAULT_CHAIN_ID);
        await awaitReceipt(client, hash, "Your claim");
        vaultLog("tx claim confirmed", { hash, token, address });
        return hash;
      } finally {
        setClaiming(false);
      }
    },
    [owner, sendBatch]
  );

  /**
   * Closes a game whose clock has run out and pays the split.
   *
   * The contract does not settle itself. The backend keeper does, within
   * seconds of expiry (measured at five on 2026-09-10), and anyone may. The
   * winner's client only sends this when the keeper has not, after a grace,
   * so a payout never depends on the keeper being up and a round normally
   * costs one settlement transaction rather than two.
   */
  const settle = useCallback(
    async (gameId: number): Promise<string> => {
      const address = owner();
      setSettling(true);
      try {
        const client = publicClientForChain(VAULT_CHAIN_ID);
        const hash = await sendBatch([settleCall(contractAddress(), gameId)], VAULT_CHAIN_ID);
        await awaitReceipt(client, hash, "Settling the round");
        vaultLog("tx settle confirmed", { gameId, hash, address });
        return hash;
      } finally {
        setSettling(false);
      }
    },
    [owner, sendBatch]
  );

  return { startGame, starting, wager, wagering, claim, claiming, settle, settling };
}
